### ISSUE TITLE
Application Run Exception when I try to run it (v1.2.4)

### ISSUE THREAD

**Issue by robinfransson** [runeberry/ValheimServerGUI#24]
![image](https://user-images.githubusercontent.com/71066647/116404897-5fda3f80-a82f-11eb-9986-d468601c4360.png)

I have never ran any version of it before at, and cannot find if I need more files than just the .exe

**Comment by dolphinspired** [comment]
Hey, thanks for letting me know! You should only need the .exe file. Someone else had this issue, and the problem was that they did not have .NET 5.0+ installed. After updating their .NET version, the error went away.

But... it looks like you have .NET 5.0.5 installed, and you're still getting that error. Very strange! I don't know what's causing it yet, but this bug report certainly helps. I will do some investigating tomorrow and get back to you.

**Comment by dolphinspired** [comment]
I'm still looking into this one. Unfortunately, I haven't been able to replicate it. And the majority of developers who have encountered this issue have encountered it when using Visual Studio, not when actually running compiled applications.

However, just today, someone posted an update in [this thread](https://github.com/dotnet/runtime/issues/48159) that *might* offer a solution. I'll keep digging and get back to you soon.

**Comment by dolphinspired** [comment]
Hey @robinfransson, I've just published v1.3.0 [here](https://github.com/runeberry/ValheimServerGUI/releases/tag/v1.3.0). Can you download it and see if this fixes your issue?

If you still get an error, you should now be prompted to submit a crash report instead of getting that big error window. Submit that and I'll keep investigating. Let me know how it goes!

**Comment by dolphinspired** [comment]
Closing this issue, assuming this is resolved since I haven't heard otherwise.
