### ISSUE TITLE
Split MainWindow tabs into seperate windows

### ISSUE THREAD

**Issue by micah686** [runeberry/ValheimServerGUI#35]
The different content within each of the tabs on the main window should be split out into usercontrols, in order to keep the code cleaner, as the application gets bigger.

**Comment by dolphinspired** [comment]
Agreed. This is my first Windows Forms application, so I'm not sure how your normally scale these things up. Putting the tab content into controls makes sense, would just have to see how that plays with dependency injection.

**Comment by micah686** [comment]
Is there a reason you went with Winforms over WPF though?

**Comment by dolphinspired** [comment]
That is a good question! Here was my reasoning:
* I only needed to target Windows Desktop.
* I wanted something I could learn in a couple of days, then develop and publish quickly. (already knew C#)
* .NET 5 is relatively new, and it's the first in the .NET Core lineage to support Windows Forms. So I was curious to see how that played with the modern tooling that I'm used to. (The answer is... "better than expected, but still not great". 😅)

I considered WPF or UWP, but they both seemed like a lot of additional overhead and setup for a relatively simple app. Maybe I was wrong about that - I'd be willing to try them for future projects. But I'm sticking with Windows Forms for this project - it gets the job done.

**Comment by micah686** [comment]
I'm working on reorganizing the tabs into their own usercontrols, as you can see here: https://github.com/micah686/ValheimServerGUI/tree/reorganize. Let me know if you have any suggestions so far on it (I'm still not done)

**Comment by dolphinspired** [comment]
Hey, I appreciate the effort - but before you go too far down this path, I want to clarify something. Are you doing this in preparation for adding some other feature? Or are you doing it just to "clean up the code"? Because I don't want this app to undergo a major refactor unless there is a compelling need for it. Lots of risk for little reward, you know?

That said, I pulled down your fork to take a look. If you want to continue going down this path, here's some stuff to keep in mind:

* There is a reason for the separate `ValheimServerGUI.Controls` project. It's so that if you're working on user controls and, something is broken (won't build), you can still build and run the main application. I found this valuable for development, so it needs to stay in.
* That said, you can absolutely make a separate folder within Forms in `ValheimServerGUI` for additional controls which are for non-reusable components specific to this UI, such as the different tab views. And the CopyButton, which is only there because it depends on an asset from the main project (the little icon).
* I don't want to see any internals used to reference services or functions on other Controls or Forms. Instead, use dependency injection to build new Controls. I would recommend registering the new Controls just like the Forms are registered on startup (see Program.cs), and adding a new method to `IFormProvider` like `GetControl<TControl>()`.
* Don't refactor or remove any existing controls as part of this effort. Keep your scope limited to: "move the Tab views into separate controls" - that's all. There should be little to no changes to the actual _content_ of the code, just which classes the code is organized in. You can certainly make PRs to enhance controls/add features later!
  * On that note... don't get rid of the LogViewer control! It's "just a TextBox", yes, but it encapsulates all the formatting/view switching logic into one place that can be embedded anywhere. Leave it in - and if you want to change how it works, do so in a separate PR after all this work is done.

If you're still interested, I would recommend starting on a fresh branch with these caveats in mind (probably easier than backing out what's in there). I'll be glad to help if you have any more questions.

**Comment by micah686** [comment]
Got it
