### ISSUE TITLE
not an issue but a feature request

### ISSUE THREAD

**Issue by friems** [runeberry/ValheimServerGUI#44]
ability to mange the server mods from the GUI
- install / remove
- enable / disable mods

**Comment by dolphinspired** [comment]
The [Vortex Mod Manager](https://www.nexusmods.com/about/vortex/) is capable of doing all this for client-side mods. Vortex doesn't seems to support dedicated server mods specifically, but I think that's because there aren't too many of them yet, and there isn't really a consistent way to configure/manage server side mods.

Regardless, I would keep an eye on Vortex for this kind of support. I don't think I'll be expanding this app to support mod management.

**Comment by friems** [comment]
Hi @dolphinspired, no worries, it could have been nice to have :)
Anyways, thanks for looking into it and making time to answer.

Keep up the good work!
